// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC-rZo4VfwXCp9DYM1U99VNoPQ1XW6ERfc',
    appId: '1:723552023518:web:9dd6b10825d69d4d69234f',
    messagingSenderId: '723552023518',
    projectId: 'hackatonapp-35304',
    authDomain: 'hackatonapp-35304.firebaseapp.com',
    storageBucket: 'hackatonapp-35304.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCOYghmuchf3IQe1JoOotIyYE9jKUvGyGo',
    appId: '1:723552023518:android:347ebf1a2685342369234f',
    messagingSenderId: '723552023518',
    projectId: 'hackatonapp-35304',
    storageBucket: 'hackatonapp-35304.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC-rZo4VfwXCp9DYM1U99VNoPQ1XW6ERfc',
    appId: '1:723552023518:web:bae85b29348b6a7069234f',
    messagingSenderId: '723552023518',
    projectId: 'hackatonapp-35304',
    authDomain: 'hackatonapp-35304.firebaseapp.com',
    storageBucket: 'hackatonapp-35304.firebasestorage.app',
  );
}
